TOP_NUMBER = 3
FILE_NAME = "rd_data.rdx"
MENU = ['Scheduled', 'View Upcoming', 'Select series', 'Add new', 'View all', 'View closing soon', 'Exit']
CHOICE_SCHEDULED = 1
CHOICE_VIEW = 2
CHOICE_SERIES = 3
CHOICE_ADD = 4
CHOICE_ALL = 5
CHOICE_CLOSING_SOON = 6
CHOICE_QUIT = 7
STATUS_OPEN = "Open"
STATUS_CLOSED = "Closed"
PREMIUM_FORMAT = " "*20+"{:^75s}".format("{:^10s}{:^30s}{:^15s}{:^20s}")
PREMIUM_HEADER = PREMIUM_FORMAT.format('Series', 'Date', 'Amount', 'Breaking')
MENU_ITEM_FORMAT = " "*20+"{:^110s}"
RD_HEADER_FORMAT = " "*20+"{:^10s}{:^30s}{:^30s}{:^15s}{:^10s}{:^15s}"
RD_HEADER = RD_HEADER_FORMAT.format('Series', 'Date', 'Maturity', 'Amount', 'Tenure', 'Status')
SEPARATOR = " "*20+"-"*110
